### ISSUE TITLE
Fix README.md

### ISSUE THREAD

**Issue by laurin-no** [rennehir/git-wand#1]
#### Issue description
The README.md is missing essential information like setting up and running the project.

#### Steps to reproduce the issue

1. Go to repository
2. Find readme with no valuable information
3. ???
4. still no clue about the project 

#### What's the expected result?

- get an overview of the project

#### What's the actual result?

- nothing

#### Additional details / screenshot

- pls fix, kiitos

**Comment by rennehir** [comment]
@lurttu can you fix?
